### ISSUE TITLE
Remove popup notifications

### ISSUE THREAD

**Issue by kairon-v** [GCES-2018-2/SIGS-GCES#11]
## Descrição do Problema
Quando volta para a página inicial, uma mensagem "você já está logado" continua aparecendo

## Comportamento Esperado
A mensagem deveria aparecer apenas no primeiro acesso a página, ou seja, após o login. Ou não deverá aparecer, já que a página indica que o usuário está logado.

## Comportamento Atual 
Mensagem "você já está logado" aparece no canto superior direito da tela, a
 cada vez que a página inicial é aberta.

## Passos Para Reproduzir o Problema

  1. Faça o login
  2. Observe a mensagem azul no canto superior direito da tela.
  3. Acesse outra página da aplicação.
  4. Na navbar, clique em SIGS e observe novamente a mensagem "Usuário já logado", no canto superior direito.

## Screenshots
<img width="317" alt="screen shot 2018-09-06 at 16 33 27" src="https://user-images.githubusercontent.com/6243672/45180732-a0a26780-b1f2-11e8-9d5c-8035a74f704e.png">

**Comment by arthurbdiniz** [comment]
na verdade, essa dialog pode ser removida.
