### ISSUE TITLE
Mostrar mensagem de inexistência de solicitações abertas

### ISSUE THREAD

**Issue by kairon-v** [GCES-2018-2/SIGS-GCES#16]
## Problem description
Não mostra uma mensagem de que não há solicitações pendentes para o usuário logado.

## Expected Behavior
Mostrar uma mensagem indicando que o usuário não possui solicitações. Exemplo: `Você não possui solicitações pendentes.`

## Current Behavior
Mostra a tabela, mas sem nenhuma mensagem ou linha com dados.

## Possible Solution
Mostrar a tabela apenas se a lista de solicitações tiver uma 

## Step to Reproduce (for _bugs_)
1. Logar numa conta de usuário.
2. Entrar na página: [https://sigsunb.herokuapp.com/my_solicitations](https://sigsunb.herokuapp.com/my_solicitations)
3. O usuário não pode ter solicitações pendentes.

## Screenshots
<img width="1229" alt="screen shot 2018-09-11 at 17 03 26" src="https://user-images.githubusercontent.com/6243672/45384715-23f1fd80-b5e5-11e8-846a-39a3e64c7d3f.png">

## Context
O usuário não consegue saber se não possui solicitações abertas ou se a tabela apenas não está mostrando.

**Comment by arthurbdiniz** [comment]
Essa issue já foi concluida!
