### ISSUE TITLE
Deploy quebrando

### ISSUE THREAD

**Issue by arthurbdiniz** [GCES-2018-2/SIGS-GCES#27]
## Problem description
Deploy está quebrando a build com problemas de chaves

## Expected Behavior
Build deveria passar

## Step to Reproduce (for _bugs_)
https://travis-ci.org/GCES-2018-2/SIGS-GCES/builds/429833025?utm_source=github_status&utm_medium=notification

## Screenshots
![image](https://user-images.githubusercontent.com/18387694/45684542-0d83fe80-bb1d-11e8-99d5-91a4f9dd8293.png)

**Comment by arthurbdiniz** [comment]
Acho que a ideia seria tirar esse deploy do heroku e fazer como deploy de imagem no docker hub

**Comment by sconetto** [comment]
@arthurbdiniz pode ser, quer que faça uma imagem do docker hub e divulgue? Criaríamos um usuário pro projeto para subir a imagem o que sugere?

**Comment by arthurbdiniz** [comment]
Deploy foi ajustado no commit 43359a55a5ca45742a90b00472050c5313397d3b
