### ISSUE TITLE
Improve Discipline selection when creating or editing a class

### ISSUE THREAD

**Issue by renatocoral** [GCES-2018-2/SIGS-GCES#283]
## Problem description

Currently while creating or editing a class, the discipline is selected by a dropdown list that is not sorted in any order. Also, many disciplines appear repeated in the list.

## Expected Behavior

A minimal expected behavior would be to sort disciplines in alphabetical order.
A better solution would be a search mechanism since when all disciplines are inserted into the system there will be thousands of disciplines to choose from.

**Comment by gustavocarvalho1002** [comment]
I took all the changes from the fork that i was working on to the main repository.
The dropdown is now sorting all the disciplines alphabetically.
I also reviewed and checked the discipline seed, where I spotted some grammar mistakes and I formatted the file.

**Comment by gustavocarvalho1002** [comment]
![Captura de tela de 2019-10-31 16-35-03](https://user-images.githubusercontent.com/23438547/67980114-7680e580-fbfc-11e9-807c-743fb4feda0b.png)
![Captura de tela de 2019-10-31 16-35-18](https://user-images.githubusercontent.com/23438547/67980115-7680e580-fbfc-11e9-8c55-ef18e8af6be8.png)
