### ISSUE TITLE
Create CRUD to update enrollment dates of each semester

### ISSUE THREAD

**Issue by renatocoral** [GCES-2018-2/SIGS-GCES#285]
## Problem description

Currently there is no front-end to update the enrollment dates which appear in the Home page.

**Comment by GeovanaRamos** [comment]
Doesn't this page solve this issue? I think it's already made @renatocoral 

![image](https://user-images.githubusercontent.com/31005087/66783722-ec701780-eeae-11e9-905a-36512fc2f8e6.png)
