### ISSUE TITLE
Improve behavior of Course association in Class CRUD

### ISSUE THREAD

**Issue by renatocoral** [GCES-2018-2/SIGS-GCES#288]
## Problem description

Currently, while creating or editing a class the method to associate a course to a class is done by a search field. But the search by name is not working and the course codes are not known. Also an empty search does not return all options.

## Expected Behavior

Implement search by course name and enable empty search to show all options.

**Comment by gustavocarvalho1002** [comment]
![buscar_curso](https://user-images.githubusercontent.com/23438547/66279288-f4183680-e886-11e9-8836-9ad49af5172a.png)

Search resulte with all the records. It show courses now when you leave the field empty and hit the search button

**Comment by gustavocarvalho1002** [comment]
I added a "Clear results" button so the user can get all the results away. It only show when there's courses showing on the screen

**Comment by gustavocarvalho1002** [comment]
![Captura de tela de 2019-10-06 22-20-10](https://user-images.githubusercontent.com/23438547/66279385-7d2f6d80-e887-11e9-88fc-6e189218ff6b.png)

**Comment by gustavocarvalho1002** [comment]
Pull request was opened for this issue!

https://github.com/SIGS-UnB/core/pull/294

**Comment by gustavocarvalho1002** [comment]
I'm moving all the code from the fork related to this issue to a new branch in the main repository

**Comment by gustavocarvalho1002** [comment]
![Captura de tela de 2019-10-28 19-46-57](https://user-images.githubusercontent.com/23438547/67723796-d8064180-f9bb-11e9-9168-2e62dcb3e6c7.png)

**Comment by gustavocarvalho1002** [comment]
trying to solve this issue with rubocop

**Comment by gustavocarvalho1002** [comment]
@arthurbdiniz. Is there any way to improve the maximum numbers of lines allowed in a class?

**Comment by arthurbdiniz** [comment]
> @arthurbdiniz. Is there any way to improve the maximum numbers of lines allowed in a class?

@gustavocarvalho1002  I think the best way is to ignore just this line on `rubocop`. You can make this via config file or with a comment inside the code. 

Follow this https://stackoverflow.com/a/26350879

**Comment by gustavocarvalho1002** [comment]
`# rubocop:disable LineLength` and `# rubocop:enable LineLength`, as well `# rubocop:disable ClassLength` and `# rubocop:disable ClassLength` didn't work. So I changed the .rubocop_todo.yml so it won't run any metrics on the school_room_controller related to the class lenght. 
I also changed the maximum rows allowed, from 88 to 100

**Comment by gustavocarvalho1002** [comment]
![Captura de tela de 2019-10-31 22-44-42](https://user-images.githubusercontent.com/23438547/67996850-1310ab00-fc30-11e9-84d5-4ea8bf16ee86.png)
![Captura de tela de 2019-10-31 22-44-49](https://user-images.githubusercontent.com/23438547/67996851-1310ab00-fc30-11e9-98a5-72be013d05b2.png)

**Comment by gustavocarvalho1002** [comment]
https://github.com/SIGS-UnB/core/pull/310 is open and waiting to be accepted!
