### ISSUE TITLE
Imagem de perfil 

### ISSUE THREAD

**Issue by arthurbdiniz** [GCES-2018-2/SIGS-GCES#34]
## Descrição
Para deixar a aplicação com uma cara mais amigável a imagem de perfil dos coordenadores poderia ajudar.
Além disso para coleta de dados essa feature poderia ajudar a identificar mais fácil

**Comment by sconetto** [comment]
Gem de upload de arquivos: 
https://www.rubydoc.info/gems/carrierwave/1.2.3
