### ISSUE TITLE
Mostrar capacidade das salas

### ISSUE THREAD

**Issue by arthurbdiniz** [GCES-2018-2/SIGS-GCES#38]
## Problem description
A visualização da capacidade das salas não está aparecendo na lista

## Expected Behavior
Que mostre a capacidade de cada sala

## Current Behavior
![image](https://user-images.githubusercontent.com/18387694/45790176-f4349c80-bc59-11e8-8e78-7bc3e1495a73.png)

**Comment by arthurbdiniz** [comment]
@sconetto acabei pegando a issue de filtros que fica no mesmo arquivo dessa issue aqui, já sei até onde alterar, queria saber se posso pegar essa issue?

**Comment by sconetto** [comment]
@arthurbdiniz claro, eu puxo uma outra issue para resolver!

**Comment by arthurbdiniz** [comment]
Obrigado
