### ISSUE TITLE
Footer escondendo parte do conteúdo das tabelas

### ISSUE THREAD

**Issue by victorcmoura** [GCES-2018-2/SIGS-GCES#59]
## Problem description
O footer está fixo, o que causa problemas na visualização de alguns componentes.
## Expected Behavior
O footer deve acompanhar o conteúdo da página.

## Current Behavior
O footer não está acompanhando o conteúdo da página.

## Screenshots
Tabela de alocação (Os horários vão até 23h59): 
![image](https://user-images.githubusercontent.com/26290053/46430273-eafa0400-c71e-11e8-8f46-4920bd75fda2.png)

**Comment by arthurbdiniz** [comment]
Footer já foi retirado
