### ISSUE TITLE
Toggle password visibility

### ISSUE THREAD

**Issue by arthurbdiniz** [GCES-2018-2/SIGS-GCES#72]
## Problem description
Botão to toggle password visibility

## Expected Behavior
Usuário conseguir ver a senha clicando em um botão

## Current Behavior
![image](https://user-images.githubusercontent.com/18387694/46739243-7cfd9180-cc76-11e8-80d2-c138599704e8.png)

## Possible Solution
https://www.w3schools.com/howto/howto_js_toggle_password.asp
![image](https://user-images.githubusercontent.com/18387694/46739347-b7672e80-cc76-11e8-8d96-43fe53548c09.png)

**Comment by bvdwalt** [comment]
Hi @arthurbdiniz where does the login page reside?

**Comment by arthurbdiniz** [comment]
Hi @bvdwalt, thank you for your interest. The password field reside in two paths, **/users/new** for **register** new users and in **localhost:3000**, where is located the **login** form.

Login Files
- **html.erb**  SIGS/app/views/sessions/new.html.erb
- **css**  SIGS/app/assets/sessions.scss
 
Register Files
- **html.erb** SIGS/app/views/users/new.html.erb
- **css**  SIGS/app/assets/user.scss

**Comment by bvdwalt** [comment]
Hi @arthurbdiniz , Thanks, I have never seen ruby on rails before, but will see what I can do.

**Comment by bvdwalt** [comment]
> Hi @bvdwalt, thank you for your interest. The password field reside in two paths, **/users/new** for **register** new users and in **localhost:3000**, where is located the **login** form.
> 
> Login Files
> 
> * **html.erb**  SIGS/app/views/sessions/new.html.erb
> * **css**  SIGS/app/assets/sessions.scss
> 
> Register Files
> 
> * **html.erb** SIGS/app/views/users/new.html.erb
> * **css**  SIGS/app/assets/user.scss

Hi @arthurbdiniz , Thanks, I have never seen ruby on rails before, but will see what I can do.

**Comment by arthurbdiniz** [comment]
> > Hi @bvdwalt, thank you for your interest. The password field reside in two paths, **/users/new** for **register** new users and in **localhost:3000**, where is located the **login** form.
> > Login Files
> > 
> > * **html.erb**  SIGS/app/views/sessions/new.html.erb
> > * **css**  SIGS/app/assets/sessions.scss
> > 
> > Register Files
> > 
> > * **html.erb** SIGS/app/views/users/new.html.erb
> > * **css**  SIGS/app/assets/user.scss
> 
> Hi @arthurbdiniz , Thanks, I have never seen ruby on rails before, but will see what I can do.

For this issue its not necessary to know ruby, the file html.erb can be written both in html and ruby.
You can create your component in the html.erb file and make it dynamic by creating a js file in the folder **SIGS/app/assets/javascripts**

**Comment by LeCeee** [comment]
i'd like to help.

**Comment by arthurbdiniz** [comment]
Hi, @LeCeee, we are glad that you have intrest in this issue. We are a Free Software Community. The first that sends the PR we do the review. 

> And of course that if you want to work in this same issue with @bvdwalt just go for it!

**Comment by bvdwalt** [comment]
> Hi, @LeCeee, we are glad that you have interest in this issue. The first that sends the PR we do the review.
> 
> > And of course that if you want to work in this issue with @bvdwalt, just go for it!

I can't seem to get docker running, I'd prefer to be able to test code before committing.

**Comment by arthurbdiniz** [comment]
> I can't seem to get docker running, I'd prefer to be able to test code before committing.

Hi @bvdwalt, we just updated the docker instructions, you can see it right [here](https://github.com/GCES-2018-2/SIGS-GCES/blob/develop/README.md)

**Comment by bvdwalt** [comment]
@arthurbdiniz I tried to follow them. But I can't even install docker, long story short, I don't have admin access on my own laptop so I can't install much. Will try get admin access by tomorrow or Monday.

**Comment by arthurbdiniz** [comment]
ok @bvdwalt

**Comment by Gass6** [comment]
Hallo @arthurbdiniz can i solve this issue?

**Comment by arthurbdiniz** [comment]
Hi @Gass6, of course, just send the PR!
