### ISSUE TITLE
Password Strength Meter

### ISSUE THREAD

**Issue by arthurbdiniz** [GCES-2018-2/SIGS-GCES#73]
## Problem description
Needs a meter to show user how secure is his password

path: /users/new

## Expected Behavior
![image](https://user-images.githubusercontent.com/18387694/46742005-8ee23300-cc7c-11e8-925a-38d7071a9da7.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/18387694/46741771-167b7200-cc7c-11e8-88d4-668441288aad.png)

## Possible Solution
https://css-tricks.com/password-strength-meter/

**Comment by fer22f** [comment]
@arthurbdiniz Doesn't make sense to me to have password strength meters in login, perhaps in some kind of signup page instead?

**Comment by arthurbdiniz** [comment]
@fer22f marquei a tela errada! Seria para a tela de cadastro

**Comment by arthurbdiniz** [comment]
@fer22f essa issue já está atualizada, obrigado pela correção!
