### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by arthurbdiniz** [GCES-2018-2/SIGS-GCES#78]
## Problem description
There is a lot of things on README that its necessary to change

## Expected Behavior
Clean README

## Current Behavior
This that its necessary to remove:
- Remove Heroku Deploy (its not been used)
- Re-link License 
- Update Docker commands with dev and prod environments
- Remove Vagrant Tutorial (its not been used)

**Comment by trevlewis** [comment]
@arthurbdiniz I can take this. Are all the environment details in the YAML files?

**Comment by arthurbdiniz** [comment]
Hi @trevlewis , thank you for your interest in our project!  😄 

All the config file for docker its in **docker-compose-dev.yml** and **docker-compose-prod.yml**.

But all you need to update on README from docker its create two topics, one with dev environment and another with production.

The outdated part is that now its necessary to pass the path of the **.yml** file:

```
$ docker-compose -f docker-compose-dev.yml build
$ docker-compose -f docker-compose-dev.yml up -d
```

**Comment by trevlewis** [comment]
@arthurbdiniz Awesome. I will get that done here in a little bit! Thank you for the information!

**Comment by arthurbdiniz** [comment]
> @arthurbdiniz Awesome. I will get that done here in a little bit! Thank you for the information!

You are welcome. Any doubt will be available right here!

**Comment by trevlewis** [comment]
Hey @arthurbdiniz would you look at this version and see if it is what you want? The indent with 4 spaces wasn't working for me for some reason so I had to use the back ticks.
[https://github.com/trevlewis/SIGS-GCES/blob/develop/README.md](https://github.com/trevlewis/SIGS-GCES/blob/develop/README.md)

**Comment by arthurbdiniz** [comment]
@trevlewis could you please send the PR? Its easier to review.

**Comment by trevlewis** [comment]
@arthurbdiniz her is the PR https://github.com/MatheusRich/SIGS-GCES/pull/99

**Comment by trevlewis** [comment]
@arthurbdiniz here is the PR https://github.com/GCES-2018-2/SIGS-GCES/pull/80

**Comment by arthurbdiniz** [comment]
@trevlewis your base fork its pointing to the wrong repository

It show be like selected GCES-2018-2/SIGS-GCES
![image](https://user-images.githubusercontent.com/18387694/46772366-0e4c2280-ccce-11e8-8355-bb76870bf6ee.png)
